language: python
python:
  - "3.9"
install:
  - pip install .[dev]
script:
  - pipdeptree
  - pytest tests/ -s --cov --cov-report xml:test-reports/coverage.xml --junitxml test-reports/pytest/tests.xml
  - coverage report -m
  - bash <(curl -s https://codecov.io/bash)
  - mypy TODO
